name: Release

on:
  push:
    tags:
      - "*"

job:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - run: ./configure
      - run: make
