name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - run: sudo apt-get install libmagick++-dev
      - run: ./configure
      - run: make
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ktech
            krane
